language: ruby
rvm:
  - 1.9.3
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rspec"
env:
  global:
    - PG_USERNAME='postgres'
    - secure: "CmMbzwj8C8PWs7PQYlJ/FxavSIgFYjGug9cxomImKLOSl3TlwQT2jd8/hZNSss9VjL/FdkwGZxF4HCKKqXVKyaITSju5bpv4uFhabY3PMEV+ry9jRJcUyE2b0YKo+G6sQXuo3TQS1/3ySWl+mlLlbwMeMAbhAFZ/xOZt5KLrcP4="
