language: ruby
rvm:
  - 1.9.3
secure: "jR5xoeu9LIZ/S6M5JByXK7n3C3caFpnoqoipDYAR5or5YGH4Hodl4etuEMbOg7X7xE/8mDfRkYigx3JuqU1Yh9FBGS7iEK4LtvuH7xifqGxiU+mkkqKhroPtI9mMZDDGpsAMw8dyDHct17qx4wjRd0rtace8BSf3WFGJ7lRiX7g="
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rspec"
env:
  - PG_USERNAME='postgres'
